# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи перестановки та символ Леві-Чивіти.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [1]:
import numpy as np
import itertools


def check(h):
    try:
        int(h)
        return True
    except ValueError:
        return False


while True:
    x = input("Input size x of matrix x*x: ")
    try:
        x = int(x)
    except ValueError:
        print("Please, enter a natural number.")
        continue
    if x < 1:
        print("Please, enter a natural number.")
    else:
        break

def matrix(x):
    """This function generates matrix and creates inversions """
    list = []
    for i in range(x):
        list.append([])
        for j in range(x):
            while True:
                try:
                    list[i].append(float(input("Input a " + str(i + 1) + str(j + 1))))
                    break
                except ValueError:
                    print("You have inputted an incorrect valur")
    matrix = np.array(list)
    print("Matrix: \n", matrix)
    return matrix


matrix = matrix(x)


l = [str(i) for i in range(1, x+1)]
maatrix = list(itertools.permutations("".join(l), x))


def f_1():
    """This function works with inversions and performs a multiplication operation"""
    global maatrix
    global x
    global matrix
    final_list = []
    for e in maatrix:
        v = 0
        index = 1
        for i in range(len(e)):
            for s in range(i):
                if e[s] > e[i]:
                    v += 1
        for i in range(len(e)):
            index = index * int(matrix[i][int(e[i])-1])
        if v % 2 == 0 or v == 0:
            final_list.append(index)
        else:
            final_list.append((-1)*(index))
    return final_list


def count():
    """This function collects results together"""
    matrix_to_print = f_1()
    finish = 0
    for i in matrix_to_print:
        finish += int(i)
    return finish


print("Det(countings): ", count())
k = np.linalg.det(matrix)
print("Det(linag.det): ", round(k, 2))


Matrix: 
 [[2. 6. 4.]
 [7. 8. 6.]
 [5. 4. 3.]]
Det(countings):  6
Det(linag.det):  6.0
